import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import localFont from 'next/font/local'
import {QuizProvider} from "@/context/QuizContext";

import "./globals.css";

const kamerik = localFont({
    src: [
        {path: '../assets/fonts/kamerik105/Kamerik105Cyrillic-Thin.woff2', weight: '100', style: 'normal'},
        {path: '../assets/fonts/kamerik105/Kamerik105Cyrillic-Light.woff2', weight: '300', style: 'normal'},
        {path: '../assets/fonts/kamerik105/Kamerik105Cyrillic-Book.woff2', weight: '400', style: 'normal'},
        {path: '../assets/fonts/kamerik105/Kamerik105Cyrillic-Bold.woff2', weight: '700', style: 'normal'},
        {path: '../assets/fonts/kamerik105/Kamerik105Cyrillic-Heavy.woff2', weight: '900', style: 'normal'},
    ],
    variable: '--font-kamerik',
    display: 'swap',
})
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fr" className={`${geistSans.variable} ${geistMono.variable} ${kamerik.variable}`}>
        <body>
        <QuizProvider>
            {children}
        </QuizProvider>
        </body>
        </html>
    );
}
